backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: /uploads
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "TA"
                name: "ta"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"
      - name: "categorias"
        label: "Categorias"
        file: "meta/categorias.yml"
        description: "List of categorias"
        fields:
          - name: categorias
            label: Categorias
            label_singular: "Categoria"
            widget: list
            fields:
              - label: "Cate"
                name: "cate"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"
      - name: "filtros"
        label: "Filtros"
        file: "meta/filtros.yml"
        description: "List of filtros"
        fields:
          - name: filtros
            label: Filtros
            label_singular: "Filtro"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "blogs"
    label: "Posts"
    folder: "content/blogs/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
      - label: "Intro"
        name: "intro"
        widget: "string"
      - label: "Language"
        name: "language"
        widget: "string"        
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.ta"
      - label: Categorias
        label_singular: "Categoria"
        name: "categorias"
        widget: list
        summary: "{{fields.categoria}}"
        field:
          label: Categoria
          name: categoria
          widget: relation
          collection: "meta"
          file: "categorias"
          searchFields:
            - "categorias.*.name"
          displayFields:
            - "categorias.*.name"
          valueField: "categorias.*.cate" 
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "recursos"
    label: "Recursos"
    folder: "content/recursos/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
      - label: "Intro"
        name: "intro"
        widget: "string"
      - label: "Language"
        name: "language"
        widget: "string"         
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Filtros
        label_singular: "Filtro"
        name: "filtros"
        widget: list
        summary: "{{fields.filtro}}"
        field:
          label: Filtro
          name: filtro
          widget: relation
          collection: "meta"
          file: "filtros"
          searchFields:
            - "filtros.*.name"
          displayFields:
            - "filtros.*.name"        
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "parceiros"
    label: "Parceiros"
    folder: "content/parceiros/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
      - label: "Intro"
        name: "intro"
        widget: "string"
      - label: "Language"
        name: "language"
        widget: "string"         
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Body"
        name: "body"
        widget: "markdown"